// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: testpb.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type M struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M) Reset() {
	*x = M{}
	mi := &file_testpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M) ProtoMessage() {}

func (x *M) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M.ProtoReflect.Descriptor instead.
func (*M) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{0}
}

func (x *M) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_testpb_proto protoreflect.FileDescriptor

const file_testpb_proto_rawDesc = "" +
	"\n" +
	"\ftestpb.proto\x12\x06testpb\"\x1d\n" +
	"\x01M\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontentB4Z2blitiri.com.ar/go/chasquid/internal/protoio/testpbb\x06proto3"

var (
	file_testpb_proto_rawDescOnce sync.Once
	file_testpb_proto_rawDescData []byte
)

func file_testpb_proto_rawDescGZIP() []byte {
	file_testpb_proto_rawDescOnce.Do(func() {
		file_testpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_proto_rawDesc), len(file_testpb_proto_rawDesc)))
	})
	return file_testpb_proto_rawDescData
}

var file_testpb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testpb_proto_goTypes = []any{
	(*M)(nil), // 0: testpb.M
}
var file_testpb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testpb_proto_init() }
func file_testpb_proto_init() {
	if File_testpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_proto_rawDesc), len(file_testpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testpb_proto_goTypes,
		DependencyIndexes: file_testpb_proto_depIdxs,
		MessageInfos:      file_testpb_proto_msgTypes,
	}.Build()
	File_testpb_proto = out.File
	file_testpb_proto_goTypes = nil
	file_testpb_proto_depIdxs = nil
}
